data:
  preprocessing: "hpf_1.5_lpf_35_baseline-on"

epoch_defaults:
  baseline: [-0.2, 0.0]

channels:
  non_scalp:
    - E1
    - E8
    - E14
    - E17
    - E21
    - E25
    - E32
    - E38
    - E43
    - E44
    - E48
    - E49
    - E56
    - E63
    - E68
    - E73
    - E81
    - E88
    - E94
    - E99
    - E107
    - E113
    - E114
    - E119
    - E120
    - E121
    - E125
    - E126
    - E127
    - E128

movie:
  fps: 5
  output_dir: "topographic_movies/topos"
  frame_window: [-0.050, 0.496]
  thumbnail:
    root: "stimuli/Stimuli for EEG-Number2013-20250715T225621Z-1-001/Stimuli for EEG-Number2013"
    metadata_key: "Prime5"
    width: 0.32
    height: 0.32
    position: [-0.35, -0.12]
    position_units: "axes"
    borderpad: 0.6

