analysis_name: "sensor_movie_increasing_vs_decreasing_within_large"
report_group: "movie_increasing_vs_decreasing_within_large"
domain: "sensor"

contrast:
  name: "Movie: Increasing vs Decreasing within Large"
  condition_A:
    name: "Increasing within Large"
    conditions: ["45", "46", "56"]
    accuracy: acc1
  condition_B:
    name: "Decreasing within Large"
    conditions: ["54", "64", "65"]
    accuracy: acc1
  combination_weights: [1, -1]

